/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsuariosRouteImport } from './routes/_app/usuarios'
import { Route as AppReceitasRouteImport } from './routes/_app/receitas'
import { Route as AppPlanosRouteImport } from './routes/_app/planos'
import { Route as AppNotificacoesRouteImport } from './routes/_app/notificacoes'
import { Route as AppImportacaoRouteImport } from './routes/_app/importacao'
import { Route as AppConfiguracoesRouteImport } from './routes/_app/configuracoes'
import { Route as AppCargosRouteImport } from './routes/_app/cargos'
import { Route as AppVendasIndexRouteImport } from './routes/_app/vendas/index'
import { Route as AppClientesIndexRouteImport } from './routes/_app/clientes/index'
import { Route as AppVendasNovaRouteImport } from './routes/_app/vendas/nova'
import { Route as AppVendasSaleIdIndexRouteImport } from './routes/_app/vendas/$saleId/index'
import { Route as AppClientesCustomerIdIndexRouteImport } from './routes/_app/clientes/$customerId/index'
import { Route as AppVendasSaleIdEditarRouteImport } from './routes/_app/vendas/$saleId/editar'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppReceitasRoute = AppReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AppRoute,
} as any)
const AppPlanosRoute = AppPlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacaoRoute = AppImportacaoRouteImport.update({
  id: '/importacao',
  path: '/importacao',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppCargosRoute = AppCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasIndexRoute = AppVendasIndexRouteImport.update({
  id: '/vendas/',
  path: '/vendas/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesIndexRoute = AppClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasNovaRoute = AppVendasNovaRouteImport.update({
  id: '/vendas/nova',
  path: '/vendas/nova',
  getParentRoute: () => AppRoute,
} as any)
const AppVendasSaleIdIndexRoute = AppVendasSaleIdIndexRouteImport.update({
  id: '/vendas/$saleId/',
  path: '/vendas/$saleId/',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesCustomerIdIndexRoute =
  AppClientesCustomerIdIndexRouteImport.update({
    id: '/clientes/$customerId/',
    path: '/clientes/$customerId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppVendasSaleIdEditarRoute = AppVendasSaleIdEditarRouteImport.update({
  id: '/vendas/$saleId/editar',
  path: '/vendas/$saleId/editar',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/cargos': typeof AppCargosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/importacao': typeof AppImportacaoRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/planos': typeof AppPlanosRoute
  '/receitas': typeof AppReceitasRoute
  '/usuarios': typeof AppUsuariosRoute
  '/vendas/nova': typeof AppVendasNovaRoute
  '/clientes/': typeof AppClientesIndexRoute
  '/vendas/': typeof AppVendasIndexRoute
  '/vendas/$saleId/editar': typeof AppVendasSaleIdEditarRoute
  '/clientes/$customerId/': typeof AppClientesCustomerIdIndexRoute
  '/vendas/$saleId/': typeof AppVendasSaleIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cargos': typeof AppCargosRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/importacao': typeof AppImportacaoRoute
  '/notificacoes': typeof AppNotificacoesRoute
  '/planos': typeof AppPlanosRoute
  '/receitas': typeof AppReceitasRoute
  '/usuarios': typeof AppUsuariosRoute
  '/': typeof AppIndexRoute
  '/vendas/nova': typeof AppVendasNovaRoute
  '/clientes': typeof AppClientesIndexRoute
  '/vendas': typeof AppVendasIndexRoute
  '/vendas/$saleId/editar': typeof AppVendasSaleIdEditarRoute
  '/clientes/$customerId': typeof AppClientesCustomerIdIndexRoute
  '/vendas/$saleId': typeof AppVendasSaleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/cargos': typeof AppCargosRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/importacao': typeof AppImportacaoRoute
  '/_app/notificacoes': typeof AppNotificacoesRoute
  '/_app/planos': typeof AppPlanosRoute
  '/_app/receitas': typeof AppReceitasRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/_app/': typeof AppIndexRoute
  '/_app/vendas/nova': typeof AppVendasNovaRoute
  '/_app/clientes/': typeof AppClientesIndexRoute
  '/_app/vendas/': typeof AppVendasIndexRoute
  '/_app/vendas/$saleId/editar': typeof AppVendasSaleIdEditarRoute
  '/_app/clientes/$customerId/': typeof AppClientesCustomerIdIndexRoute
  '/_app/vendas/$saleId/': typeof AppVendasSaleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/cargos'
    | '/configuracoes'
    | '/importacao'
    | '/notificacoes'
    | '/planos'
    | '/receitas'
    | '/usuarios'
    | '/vendas/nova'
    | '/clientes/'
    | '/vendas/'
    | '/vendas/$saleId/editar'
    | '/clientes/$customerId/'
    | '/vendas/$saleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cargos'
    | '/configuracoes'
    | '/importacao'
    | '/notificacoes'
    | '/planos'
    | '/receitas'
    | '/usuarios'
    | '/'
    | '/vendas/nova'
    | '/clientes'
    | '/vendas'
    | '/vendas/$saleId/editar'
    | '/clientes/$customerId'
    | '/vendas/$saleId'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/cargos'
    | '/_app/configuracoes'
    | '/_app/importacao'
    | '/_app/notificacoes'
    | '/_app/planos'
    | '/_app/receitas'
    | '/_app/usuarios'
    | '/_app/'
    | '/_app/vendas/nova'
    | '/_app/clientes/'
    | '/_app/vendas/'
    | '/_app/vendas/$saleId/editar'
    | '/_app/clientes/$customerId/'
    | '/_app/vendas/$saleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/receitas': {
      id: '/_app/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AppReceitasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planos': {
      id: '/_app/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof AppPlanosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notificacoes': {
      id: '/_app/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/importacao': {
      id: '/_app/importacao'
      path: '/importacao'
      fullPath: '/importacao'
      preLoaderRoute: typeof AppImportacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cargos': {
      id: '/_app/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AppCargosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/': {
      id: '/_app/vendas/'
      path: '/vendas'
      fullPath: '/vendas/'
      preLoaderRoute: typeof AppVendasIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/': {
      id: '/_app/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AppClientesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/nova': {
      id: '/_app/vendas/nova'
      path: '/vendas/nova'
      fullPath: '/vendas/nova'
      preLoaderRoute: typeof AppVendasNovaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/$saleId/': {
      id: '/_app/vendas/$saleId/'
      path: '/vendas/$saleId'
      fullPath: '/vendas/$saleId/'
      preLoaderRoute: typeof AppVendasSaleIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes/$customerId/': {
      id: '/_app/clientes/$customerId/'
      path: '/clientes/$customerId'
      fullPath: '/clientes/$customerId/'
      preLoaderRoute: typeof AppClientesCustomerIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendas/$saleId/editar': {
      id: '/_app/vendas/$saleId/editar'
      path: '/vendas/$saleId/editar'
      fullPath: '/vendas/$saleId/editar'
      preLoaderRoute: typeof AppVendasSaleIdEditarRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCargosRoute: typeof AppCargosRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppImportacaoRoute: typeof AppImportacaoRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppPlanosRoute: typeof AppPlanosRoute
  AppReceitasRoute: typeof AppReceitasRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppVendasNovaRoute: typeof AppVendasNovaRoute
  AppClientesIndexRoute: typeof AppClientesIndexRoute
  AppVendasIndexRoute: typeof AppVendasIndexRoute
  AppVendasSaleIdEditarRoute: typeof AppVendasSaleIdEditarRoute
  AppClientesCustomerIdIndexRoute: typeof AppClientesCustomerIdIndexRoute
  AppVendasSaleIdIndexRoute: typeof AppVendasSaleIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCargosRoute: AppCargosRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppImportacaoRoute: AppImportacaoRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppPlanosRoute: AppPlanosRoute,
  AppReceitasRoute: AppReceitasRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
  AppVendasNovaRoute: AppVendasNovaRoute,
  AppClientesIndexRoute: AppClientesIndexRoute,
  AppVendasIndexRoute: AppVendasIndexRoute,
  AppVendasSaleIdEditarRoute: AppVendasSaleIdEditarRoute,
  AppClientesCustomerIdIndexRoute: AppClientesCustomerIdIndexRoute,
  AppVendasSaleIdIndexRoute: AppVendasSaleIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
