import { HttpStatus } from "@nestjs/common";

export enum ErrorCode {
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INVALID_INPUT = "INVALID_INPUT",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",
  INVALID_OPERATION = "INVALID_OPERATION",
  CONFLICT = "CONFLICT",
  PAYLOAD_TOO_LARGE = "PAYLOAD_TOO_LARGE",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  USER_INACTIVE = "USER_INACTIVE",
  INVALID_TOKEN = "INVALID_TOKEN",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",
  PERMISSION_KEY_UNKNOWN = "PERMISSION_KEY_UNKNOWN",
  ROLE_NAME_TAKEN = "ROLE_NAME_TAKEN",
  ROLE_HAS_USERS = "ROLE_HAS_USERS",
  ROLE_NOT_FOUND = "ROLE_NOT_FOUND",
  OWN_ROLE_CHANGE_FORBIDDEN = "OWN_ROLE_CHANGE_FORBIDDEN",
  DOMAIN_VALUE_DUPLICATE = "DOMAIN_VALUE_DUPLICATE",
  DOMAIN_VALUE_INVALID = "DOMAIN_VALUE_INVALID",
  DOMAIN_VALUE_ORDER_INVALID = "DOMAIN_VALUE_ORDER_INVALID",
  SETTING_KEY_UNKNOWN = "SETTING_KEY_UNKNOWN",
  PLAN_NAME_TAKEN = "PLAN_NAME_TAKEN",
  PLAN_PRICE_RANGE_INVALID = "PLAN_PRICE_RANGE_INVALID",
  PLAN_INVALID = "PLAN_INVALID",
  PLAN_TYPE_INVALID = "PLAN_TYPE_INVALID",
  USER_EMAIL_TAKEN = "USER_EMAIL_TAKEN",
  USER_CPF_TAKEN = "USER_CPF_TAKEN",
  USER_REFERENCE_TAKEN = "USER_REFERENCE_TAKEN",
  USER_PROTECTED = "USER_PROTECTED",
  SUPER_ADMIN_DEACTIVATION_FORBIDDEN = "SUPER_ADMIN_DEACTIVATION_FORBIDDEN",
  PASSWORD_CHANGE_FORBIDDEN = "PASSWORD_CHANGE_FORBIDDEN",
  SALE_AMOUNT_OUT_OF_RANGE = "SALE_AMOUNT_OUT_OF_RANGE",
  SALE_BANK_DATA_REQUIRED = "SALE_BANK_DATA_REQUIRED",
  SALE_PAYMENT_METHOD_REQUIRED = "SALE_PAYMENT_METHOD_REQUIRED",
  SALE_PLAN_REQUIRED = "SALE_PLAN_REQUIRED",
  SALE_ADDRESS_REQUIRED = "SALE_ADDRESS_REQUIRED",
  SALE_PERSON_NOT_ELIGIBLE = "SALE_PERSON_NOT_ELIGIBLE",
  SALE_ALREADY_CANCELED = "SALE_ALREADY_CANCELED",
  SALE_CANCELED_STATUS_MISSING = "SALE_CANCELED_STATUS_MISSING",
  SALE_NOT_FOUND = "SALE_NOT_FOUND",
  CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND",
  CUSTOMER_CPF_TAKEN = "CUSTOMER_CPF_TAKEN",
  ADDRESS_NOT_FOUND = "ADDRESS_NOT_FOUND",
  POSTAL_CODE_NOT_FOUND = "POSTAL_CODE_NOT_FOUND",
  POSTAL_CODE_LOOKUP_FAILED = "POSTAL_CODE_LOOKUP_FAILED",
  ATTACHMENT_TYPE_INVALID = "ATTACHMENT_TYPE_INVALID",
  ATTACHMENT_TOO_LARGE = "ATTACHMENT_TOO_LARGE",
  ATTACHMENT_NOT_FOUND = "ATTACHMENT_NOT_FOUND",
  ATTACHMENT_FORBIDDEN = "ATTACHMENT_FORBIDDEN",
  IMPORT_HEADER_INVALID = "IMPORT_HEADER_INVALID",
  IMPORT_FILE_REQUIRED = "IMPORT_FILE_REQUIRED",
  IMPORT_FILE_EMPTY = "IMPORT_FILE_EMPTY",
  IMPORT_FILE_TOO_LARGE = "IMPORT_FILE_TOO_LARGE",
  IMPORT_MAPPING_DUPLICATE = "IMPORT_MAPPING_DUPLICATE",
  IMPORT_MAPPING_TARGET_INVALID = "IMPORT_MAPPING_TARGET_INVALID",
  IMPORT_BATCH_NOT_FOUND = "IMPORT_BATCH_NOT_FOUND",
  IMPORT_IN_PROGRESS = "IMPORT_IN_PROGRESS",
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",
  NOTIFICATION_SOUND_REQUIRED = "NOTIFICATION_SOUND_REQUIRED",
  NOTIFICATION_SOUND_TYPE_INVALID = "NOTIFICATION_SOUND_TYPE_INVALID",
  NOTIFICATION_SOUND_TOO_LARGE = "NOTIFICATION_SOUND_TOO_LARGE",
}

interface ErrorDefinition {
  status: HttpStatus;
  message: string;
}

const { BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND, CONFLICT } = HttpStatus;

export const ERROR_DEFINITIONS: Record<ErrorCode, ErrorDefinition> = {
  UNAUTHORIZED: { status: UNAUTHORIZED, message: "Não autenticado" },
  FORBIDDEN: { status: FORBIDDEN, message: "Sem permissão para esta ação" },
  INVALID_INPUT: { status: BAD_REQUEST, message: "Dados inválidos" },
  RESOURCE_NOT_FOUND: { status: NOT_FOUND, message: "Registro não encontrado" },
  INVALID_OPERATION: {
    status: CONFLICT,
    message: "Não é possível concluir: registro relacionado inválido ou em uso",
  },
  CONFLICT: { status: CONFLICT, message: "Já existe um registro com esses dados" },
  PAYLOAD_TOO_LARGE: {
    status: HttpStatus.PAYLOAD_TOO_LARGE,
    message: "Arquivo excede o limite permitido",
  },
  TOO_MANY_REQUESTS: {
    status: HttpStatus.TOO_MANY_REQUESTS,
    message: "Muitas tentativas. Aguarde um momento e tente de novo",
  },
  UNKNOWN_ERROR: {
    status: HttpStatus.INTERNAL_SERVER_ERROR,
    message: "Erro inesperado. Tente novamente",
  },
  INVALID_CREDENTIALS: { status: UNAUTHORIZED, message: "Credenciais inválidas" },
  USER_INACTIVE: { status: FORBIDDEN, message: "Conta inativa" },
  INVALID_TOKEN: { status: UNAUTHORIZED, message: "Token inválido" },
  TOKEN_EXPIRED: { status: UNAUTHORIZED, message: "Token expirado" },
  PERMISSION_KEY_UNKNOWN: { status: BAD_REQUEST, message: "Permissões desconhecidas" },
  ROLE_NAME_TAKEN: { status: CONFLICT, message: "Nome de cargo já existe" },
  ROLE_HAS_USERS: { status: CONFLICT, message: "Cargo possui usuários atribuídos" },
  ROLE_NOT_FOUND: { status: BAD_REQUEST, message: "Cargo não encontrado" },
  OWN_ROLE_CHANGE_FORBIDDEN: {
    status: FORBIDDEN,
    message: "Você não pode alterar o próprio cargo",
  },
  DOMAIN_VALUE_DUPLICATE: { status: CONFLICT, message: "Valor já cadastrado para este tipo" },
  DOMAIN_VALUE_INVALID: { status: BAD_REQUEST, message: "Valor de domínio inválido ou inativo" },
  DOMAIN_VALUE_ORDER_INVALID: {
    status: BAD_REQUEST,
    message: "Lista de ordem incompleta ou inválida",
  },
  SETTING_KEY_UNKNOWN: { status: BAD_REQUEST, message: "Configuração desconhecida" },
  PLAN_NAME_TAKEN: { status: CONFLICT, message: "Já existe um plano com esse nome" },
  PLAN_PRICE_RANGE_INVALID: {
    status: BAD_REQUEST,
    message: "Preço mínimo não pode ser maior que o preço base",
  },
  PLAN_INVALID: { status: BAD_REQUEST, message: "Plano inválido ou inativo" },
  PLAN_TYPE_INVALID: { status: BAD_REQUEST, message: "Tipo de plano inválido ou inativo" },
  USER_EMAIL_TAKEN: { status: CONFLICT, message: "Já existe um usuário com esse e-mail" },
  USER_CPF_TAKEN: { status: CONFLICT, message: "Já existe um usuário com esse CPF" },
  USER_REFERENCE_TAKEN: { status: CONFLICT, message: "Referência já em uso" },
  USER_PROTECTED: {
    status: FORBIDDEN,
    message: "O usuário administrador do sistema não pode ser alterado",
  },
  SUPER_ADMIN_DEACTIVATION_FORBIDDEN: {
    status: FORBIDDEN,
    message: "Não é possível desativar um super admin",
  },
  PASSWORD_CHANGE_FORBIDDEN: {
    status: FORBIDDEN,
    message: "Sem permissão para alterar a senha deste usuário",
  },
  SALE_AMOUNT_OUT_OF_RANGE: { status: BAD_REQUEST, message: "Valor fora da faixa do plano" },
  SALE_BANK_DATA_REQUIRED: {
    status: BAD_REQUEST,
    message: "Dados bancários incompletos para débito automático",
  },
  SALE_PAYMENT_METHOD_REQUIRED: { status: BAD_REQUEST, message: "Selecione a forma de pagamento" },
  SALE_PLAN_REQUIRED: { status: BAD_REQUEST, message: "Selecione um plano" },
  SALE_ADDRESS_REQUIRED: { status: BAD_REQUEST, message: "Endereço incompleto" },
  SALE_PERSON_NOT_ELIGIBLE: {
    status: BAD_REQUEST,
    message: "Esta pessoa não pode ocupar essa função na venda",
  },
  SALE_ALREADY_CANCELED: { status: BAD_REQUEST, message: "Venda já cancelada" },
  SALE_CANCELED_STATUS_MISSING: {
    status: BAD_REQUEST,
    message: "Status CANCELADA não cadastrado nas configurações",
  },
  SALE_NOT_FOUND: { status: NOT_FOUND, message: "Venda não encontrada" },
  CUSTOMER_NOT_FOUND: { status: NOT_FOUND, message: "Cliente não encontrado" },
  CUSTOMER_CPF_TAKEN: { status: CONFLICT, message: "Já existe um cliente com esse CPF/CNPJ" },
  ADDRESS_NOT_FOUND: { status: BAD_REQUEST, message: "Endereço não encontrado" },
  POSTAL_CODE_NOT_FOUND: { status: NOT_FOUND, message: "CEP não encontrado" },
  POSTAL_CODE_LOOKUP_FAILED: {
    status: HttpStatus.SERVICE_UNAVAILABLE,
    message: "Não foi possível consultar o CEP agora",
  },
  ATTACHMENT_TYPE_INVALID: { status: BAD_REQUEST, message: "Tipo de arquivo não permitido" },
  ATTACHMENT_TOO_LARGE: { status: BAD_REQUEST, message: "Arquivo excede o limite permitido" },
  ATTACHMENT_NOT_FOUND: { status: NOT_FOUND, message: "Anexo não encontrado" },
  ATTACHMENT_FORBIDDEN: {
    status: FORBIDDEN,
    message: "Sem permissão para anexar arquivos nesta venda",
  },
  IMPORT_HEADER_INVALID: { status: BAD_REQUEST, message: "Cabeçalho da planilha não reconhecido" },
  IMPORT_FILE_REQUIRED: { status: BAD_REQUEST, message: "Envie o arquivo da planilha" },
  IMPORT_FILE_EMPTY: { status: BAD_REQUEST, message: "Planilha vazia" },
  IMPORT_FILE_TOO_LARGE: {
    status: HttpStatus.PAYLOAD_TOO_LARGE,
    message: "Planilha excede o limite permitido",
  },
  IMPORT_MAPPING_DUPLICATE: { status: CONFLICT, message: "Mapeamento já existe" },
  IMPORT_MAPPING_TARGET_INVALID: {
    status: BAD_REQUEST,
    message: "Alvo do mapeamento não encontrado",
  },
  IMPORT_BATCH_NOT_FOUND: { status: NOT_FOUND, message: "Lote não encontrado" },
  IMPORT_IN_PROGRESS: { status: CONFLICT, message: "Já existe uma importação em andamento" },
  NOTIFICATION_NOT_FOUND: { status: NOT_FOUND, message: "Notificação não encontrada" },
  NOTIFICATION_SOUND_REQUIRED: { status: BAD_REQUEST, message: "Envie o arquivo de som" },
  NOTIFICATION_SOUND_TYPE_INVALID: {
    status: BAD_REQUEST,
    message: "Formato não suportado. Envie um arquivo MP3, OGG ou WAV",
  },
  NOTIFICATION_SOUND_TOO_LARGE: {
    status: HttpStatus.PAYLOAD_TOO_LARGE,
    message: "Arquivo excede o limite permitido",
  },
};
